[Dont merge] Update UI to match new dashboard style
saleor/apps pull request #138
Opened 2023-02-10 10:51 UTC by lkostrowski

Updated for few apps - some of them failed with theme provider

Merge this when dashboard is merged

2023-02-14 15:22 UTC, krzysztofwolski requested changes

2023-02-14 15:22 UTC, krzysztofwolski commented on apps/klaviyo/pages/_app.tsx
> +  productionPrefix: "c",
What `c` stands for? :thinking:

2023-02-14 15:22 UTC, krzysztofwolski commented on apps/search/src/pages/_app.tsx
> + * todo use from packages/shared
```suggestion
 * TODO: use from packages/shared
```

It's a nitpick, but with such formatting y editor automatically highlights the line :)

2023-02-14 15:22 UTC, krzysztofwolski commented on .changeset/shy-gorillas-shop.md
> +"@saleor/apps-shared": minor
Apps depending on shared module probably should be added in this note too.

2023-02-14 15:36 UTC, lkostrowski commented on apps/klaviyo/pages/_app.tsx
> +  productionPrefix: "c",
It was copy pasted from stack overflow 😆 

Bascially its some workaround to material/jss that scopes generated styles so they don't conflict. 
Without that, code from `packages/shared` was duplicating classnames

2023-02-21 10:34 UTC, krzysztofwolski approved these changes

2023-02-21 10:34 UTC, merged