Add pkg linter
saleor/apps pull request #1464
Opened 2024-07-04 10:22 UTC by krzysztofzuraw

## Scope of the PR

## Related issues

## Checklist

- [ ] I added changesets and [read good practices](/.changeset/README.md).

2024-07-04 12:24 UTC, witoszekdev approved these changes

2024-07-04 12:27 UTC, lkostrowski requested changes
can you pin all packages? Now its partially pinned

2024-07-04 12:27 UTC, lkostrowski commented on apps/search/package.json
>      "clsx": "^1.2.1",
Shouldnt you pin all dependencies? I see only some of them are pinned

2024-07-04 18:36 UTC, lkostrowski requested changes
Maybe we can also add this rule
https://github.com/kellyselden/eslint-plugin-json-files/blob/main/docs/rules/restrict-ranges.md

or the new linter will handle this? I think from now on, PR should fail to build if packages are not pinned

Also, we should probably fix typescript first and rebase

2024-07-05 10:09 UTC, krzysztofzuraw commented
We decided to move pinning versions to other PR

2024-07-05 10:42 UTC, krzysztofzuraw commented
I'm closing this PR - I will first install linter and in other PR I will this its errors

2024-07-05 10:42 UTC, closed without merging