Add/Update README files
saleor/apps pull request #1488
Opened 2024-07-23 21:39 UTC by poulch

## Scope of the PR

## Related issues

## Checklist

- [ ] I added changesets and [read good practices](/.changeset/README.md).

2024-07-24 15:34 UTC, andrzejewsky requested changes

2024-07-24 15:34 UTC, andrzejewsky commented on apps/cms-v2/README.md
> +[Here](./docs/testing.md) you can find doc how to test the app
I think this is not testing, this is rather configuration for each cms provider, I would recommend to rename it to something like "Providers configuration"

2024-07-24 15:34 UTC, andrzejewsky commented on apps/cms-v2/README.md
> +[Here](./docs/testing.md) you can find doc how to test the app
it applies also for other apps's readme

2024-07-24 15:34 UTC, andrzejewsky commented on apps/cms-v2/README.md
> +5. Tunnel the app and install it on the Saleor dashboard.
can you attach the command for it?

2024-07-24 15:34 UTC, andrzejewsky commented on apps/cms-v2/README.md
> +5. Tunnel the app and install it on the Saleor dashboard.
what does it mean "install it on the Saleor dashbaord", paste link to the manifest and install?

2024-07-24 15:34 UTC, andrzejewsky commented on apps/klaviyo/README.md
> +  <p>Simple Klaviyo example app for Saleor</p>
example app? we use it on prod so this is not "example" anymore

2024-07-24 15:34 UTC, andrzejewsky commented on apps/cms-v2/README.md
> +2. Create a file named `.env` and use the contents of the [`.env.example`](./.env.example) file as a reference. Set you `SECRET_KEY` in [`.env`](./.env)
`.env.example` says that SECRET_KEY is required only for production build

2024-07-24 15:34 UTC, andrzejewsky commented on apps/cms-v2/README.md
> +2. Create a file named `.env` and use the contents of the [`.env.example`](./.env.example) file as a reference. Set you `SECRET_KEY` in [`.env`](./.env)
`APP_API_BASE_URL` and `APP_IFRAME_BASE_URL` - sounds like something to configure

2024-07-24 15:34 UTC, andrzejewsky commented on apps/data-importer/docs/testing.md
> +## How to test Data importer app
this app is actually an integration with the nuvo, but you don't mention it at all

2024-07-24 15:34 UTC, andrzejewsky commented on apps/data-importer/README.md
> +2. Create a file named `.env` and use the contents of the [`.env.example`](./.env.example) file as a reference. Set you `NEXT_PUBLIC_NUVO_LICENSE_KEY` in [`.env`](./.env)
where can i that license key?

2024-07-25 16:13 UTC, Cloud11PL commented on apps/smtp/docs/configuration.md
> +To configure app you need SMTP server, you can run it locally using docker
```suggestion
To configure the app you need an SMTP server. You can run it locally using Docker.
```

2024-07-25 18:16 UTC, Cloud11PL approved these changes

2024-07-26 06:17 UTC, krzysztofzuraw reviewed
We can change node version to 20.x in READMEs

2024-07-26 06:17 UTC, krzysztofzuraw commented on apps/cms-v2/README.md
> +- [node v16](http://nodejs.com)
```suggestion
- [node v20](http://nodejs.com)
```

2024-07-26 07:31 UTC, Cloud11PL submitted a review, later dismissed

2024-07-26 07:34 UTC, krzysztofzuraw submitted a review, later dismissed

2024-07-26 08:09 UTC, andrzejewsky approved these changes

2024-07-26 08:14 UTC, Cloud11PL approved these changes

2024-07-26 08:17 UTC, krzysztofzuraw approved these changes

2024-07-26 08:19 UTC, merged

2024-07-26 08:21 UTC, andrzejewsky approved these changes