Remove email and messages app from monorepo
saleor/apps pull request #1503
Opened 2024-08-02 14:33 UTC by poulch

## Scope of the PR

## Related issues

## Checklist

- [ ] I added changesets and [read good practices](/.changeset/README.md).

2024-08-08 13:33 UTC, lkostrowski requested changes
Lets first officially create repo with example, add it to docs etc, then we need to check who is using this app. Then, we can remove code and proceed to shut down deployment

2024-08-08 13:46 UTC, poulch commented
> Lets first officially create repo with example, add it to docs etc, then we need to check who is using this app. Then, we can remove code and proceed to shut down deployment

Repo is mentioned in README, here is link https://github.com/saleor/example-app-sendgrid

2024-08-21 10:14 UTC, lkostrowski approved these changes

2024-08-21 10:46 UTC, Cloud11PL approved these changes

2024-08-21 11:00 UTC, stmpn approved these changes

2024-08-21 11:42 UTC, merged