Update design to new Macaw
saleor/apps pull request #426
Opened 2023-04-26 07:42 UTC by krzysztofwolski

2023-04-26 16:38 UTC, lkostrowski requested changes

2023-04-26 16:38 UTC, lkostrowski commented on apps/emails-and-messages/src/lib/is-available-in-channel.ts
> +export const isAvailableInChannel = ({
please add test

2023-04-26 16:38 UTC, lkostrowski commented on apps/emails-and-messages/src/modules/app-configuration/ui/provider-selection-box.tsx
> +      <Box
we can consider `CenterBox` which will be flex/grid that centers its children

2023-04-26 16:38 UTC, lkostrowski commented on apps/emails-and-messages/src/modules/sendgrid/configuration/sendgrid-config-container.ts
>      return filtered;
I think this code is duplicated - should be extracted, because it contains some shared behavior

2023-05-31 15:18 UTC, krzysztofwolski commented
Closing the PR - scope has been covered in base PR

2023-05-31 16:08 UTC, merged