Update design of the Sendgrid module
saleor/apps pull request #427
Opened 2023-04-26 07:48 UTC by krzysztofwolski

2023-04-27 06:51 UTC, lkostrowski requested changes
partial review - I believe this PR target should not be `main`?

2023-04-27 06:51 UTC, lkostrowski commented on apps/emails-and-messages/src/components/breadcrumbs.tsx
> +  // TODO: do I have to recreate the array here?
yes becasue pop() mutates the prop

2023-04-27 06:51 UTC, lkostrowski commented on apps/emails-and-messages/src/components/temp.tsx
> +            <Text display="block">
you can also write semantic `as="p"` that will render it properly, because `<p>` is block too

2023-04-27 06:51 UTC, lkostrowski commented on apps/emails-and-messages/src/lib/is-available-in-channel.ts
> +export const isAvailableInChannel = ({
please add test

2023-05-04 15:53 UTC, lkostrowski requested changes

2023-05-31 15:19 UTC, krzysztofwolski commented
Closing the PR - scope has been covered in base PR

2023-05-31 15:19 UTC, closed without merging