Sentry improvements
saleor/apps pull request #652
Opened 2023-06-16 13:35 UTC by lkostrowski

## Checklist
* [ ] `.github/dependabot.yaml` is up-to date.
* [ ] I added changesets and [read good practices](/.changeset/README.md).

2023-06-19 14:34 UTC, krzysztofwolski requested changes

2023-06-19 14:37 UTC, lkostrowski commented on apps/cms/src/pages/home.tsx
> +            TEST ERROR SENTRY
of course not 😆 fixing

2023-06-19 14:39 UTC, lkostrowski commented on apps/cms/src/pages/home.tsx
> +            TEST ERROR SENTRY
however @krzysztofwolski & @peelar please take a look at this example how to create a meaningful Sentry errors

```
Sentry.withScope((scope) => {
                scope.setUser({
                  segment: appBridgeState?.domain,
                });

                scope.setContext("app-bridge-state", {
                  appId: appBridgeState?.id,
                  locale: appBridgeState?.locale,
                });

                scope.addBreadcrumb({
                  level: "warning",
                  data: {},
                  message: "User clicked error test button",
                });

                Sentry.captureException(new Error("Test event from CMS app"));
```

2023-06-19 14:39 UTC, lkostrowski commented on apps/cms/src/pages/home.tsx
> +            TEST ERROR SENTRY
We can work on some abstractions later (useSentry hook with its context etc)

2023-06-19 15:28 UTC, lkostrowski commented on apps/cms/src/pages/home.tsx
> +            TEST ERROR SENTRY
fixed

2023-06-20 06:42 UTC, peelar reviewed
We could use some context about what exactly are we improving in our Sentry setup

2023-06-20 06:42 UTC, peelar commented on apps/cms/src/providers/GraphQLProvider.tsx
> +>>>>>>> ab0d55dd (Update Sentry in CMS)
something is no yes here

2023-06-20 08:02 UTC, peelar approved these changes

2023-06-20 08:06 UTC, merged