Introduce Apps CLI development tool
saleor/apps pull request #675
Opened 2023-06-26 10:43 UTC by krzysztofwolski

## Scope of the PR

The CLI is a result of our internal hackathon. It's purpose:
- install an application from the command line
- remove single or all apps
- debug webhook deliveries

## Related issues

## Checklist

- [ ] `.github/dependabot.yaml` is up-to date.
- [ ] I added changesets and [read good practices](/.changeset/README.md).

2023-06-26 14:12 UTC, krzysztofwolski commented
Failing tests seem to be caused by desynchronized dependencies. Created fix in separate PR to avoid polluting the context of this PR: #676

2023-06-27 06:33 UTC, peelar reviewed
amazing 😍

2023-06-27 06:33 UTC, peelar commented on .changeset/funny-fireants-turn.md
> +The app is intended to help with common tasks in app development, like installing apps from manifest or debugging webhooks.
```suggestion
This tool is intended to help with common tasks in app development, like installing apps from manifest or debugging webhooks.
```

a bit too many "app"s

2023-06-27 06:33 UTC, peelar commented on apps/apps-cli/src/lib/install-and-wait-for-result.ts
> + * If will throw error if any of the steps fails.
```suggestion
 * It will throw error if any of the steps fails.
```

2023-06-28 08:35 UTC, lkostrowski requested changes
First part of the review

2023-06-28 08:35 UTC, lkostrowski commented on apps/apps-cli/.env.example
> +USER_PASSWORD=password123
I'm not sure if it works like intended. This assumes we have only one env we are working with.

The important case is to target many envs, so I can install app on multiple Saleor versions

2023-06-28 08:35 UTC, lkostrowski commented on apps/apps-cli/.gitignore
I dont think this file is even needed. If CLI adds some specific artifacts, only mention this one

2023-06-28 08:35 UTC, lkostrowski commented on apps/apps-cli/codegen.ts
> +  schema: "https://demo.saleor.io/graphql/",
why do we hardcode demo?

2023-06-28 08:35 UTC, lkostrowski commented on apps/apps-cli/package.json
> +    "watch-esbuild": "esbuild --watch src/cli.ts --bundle --minify --outfile=dist/apps-cli.js --platform=node --format=esm --target=node18 --banner:js=\"import { createRequire } from 'module';const r
Do we need this? I think its copy-pasted from saleor/cli and I don't want to replicate its patterns

2023-06-28 08:35 UTC, lkostrowski commented on apps/apps-cli/package.json
> +    "build": "pnpm bundle",
Do we actually need to *build* this? What for?

2023-06-28 08:35 UTC, lkostrowski commented on apps/apps-cli/src/cli.ts
> +#!/usr/bin/env node
is it really required? Its `ts` file

2023-06-28 08:35 UTC, lkostrowski commented on apps/apps-cli/src/cli.ts
> +import "dotenv/config";
dotenv/config should be first line, beacuae 

```
import { installAppCommand } from "./commands/install-app-command";
import { uninstallAppCommand } from "./commands/uninstall-app-command";
```

these will not have access to .env

2023-06-28 08:35 UTC, lkostrowski commented on apps/apps-cli/src/commands/install-app-command.ts
> +  console.log(`App ${installedAppData.name} (${installedAppData.id}) installed!`);
Lets log a clickable link do apps and apps/id

2023-06-28 08:35 UTC, lkostrowski commented on apps/apps-cli/src/lib/install-and-wait-for-result.ts
> +    await delay(2000);
Lets make these times shorter, like 500ms. We will install apps in batch so it will really take time

2023-06-28 08:35 UTC, lkostrowski commented on apps/apps-cli/src/commands/install-app-command.ts
> +  const token = await getAccessTokenMutation({
AFAIK each time you log in, you invalidate previous token. Its not a big deal when you need to log in to dashboard again. But what if I want to install 10 apps? I will have to run CLI 10 times. Each next run will cause previous one to fail.

We need "batch install"  command to install multiple apps at once with single log in

2023-06-28 08:35 UTC, lkostrowski commented on apps/apps-cli/src/saleor-api/operations/get-access-token-mutation.ts
> +      refreshToken
we dont need refresh token

2023-06-28 10:37 UTC, lkostrowski requested changes

2023-06-28 10:37 UTC, lkostrowski commented on apps/apps-cli/src/saleor-api/operations/get-app-installations-list-query.ts
> +const getAppInstallationsQueryDocument = graphql(/* GraphQL */ `
comment?

2023-06-28 10:37 UTC, lkostrowski commented on apps/apps-cli/src/saleor-api/operations/get-app-installations-list-query.ts
> +  const { appsInstallations } = await request(
maybe we can reuse createClient from urql?

2024-04-18 07:39 UTC, closed without merging